from decouple import config

EVENTBRITE_TOKEN = config("EVENTBRITE_TOKEN")
EVENTBRITE_EVENT_ID = config("EVENTBRITE_EVENT_ID")
GOOGLE_SERVICE_ACCOUNT = config("GOOGLE_SERVICE_ACCOUNT")
SAMPLE_SPREADSHEET_ID = config("SAMPLE_SPREADSHEET_ID")
EVENTBRITE_ATTENDES_URL = config("EVENTBRITE_ATTENDES_URL")
