version: "3.9"
   
services:
  eventbrite_api:
    container_name: eventbrite_apidocke
    build: .
    ports:
      - "0.0.0.0:8080:8080"
    env_file: .env
    command: uvicorn app.main:app --reload --workers 1 --host=0.0.0.0 --port 8080    
